export const ClientEvents = {
  JOIN_GAME: "join-game",
  RECONNECT_GAME: "reconnect-game",
  LEAVE_GAME: "leave-game",
  CONFIRM_START: "confirm-start",
  CANCEL_START: "cancel-start",
  DRAW_CARD: "draw-card",
  PLAY_CARD: "play-card",
  PLAY_COMBO: "play-combo",
  PLAY_DEFUSE: "play-defuse",
  INSERT_KITTEN: "insert-kitten",
  PLAY_NOPE: "play-nope",
  SELECT_PLAYER: "select-player",
  SEEN_THE_FUTURE: "seen-the-future",
  CHOOSE_CARD_ID: "choose-card-id",
  CHOOSE_CARD_INDEX: "choose-card-index",
  CHOOSE_CARD_TYPE: "choose-card-type",
} as const;

export const ServerPublicEvents = {
  LOBBY_GAME_UPDATED: "lobby-game-updated",
  LOBBY_GAME_REMOVED: "lobby-game-removed",
  PLAYER_JOINED: "player-joined",
  PLAYER_LEFT: "player-left",
  PLAYER_DISCONNECTED: "player-disconnected",
  PLAYER_RECONNECTED: "player-reconnected",
  PLAYER_CONFIRMED: "player-confirmed",
  PLAYER_CANCELED: "player-canceled",
  COUNTDOWN_STARTED: "countdown-started",
  COUNTDOWN_CANCELED: "countdown-canceled",
  CARD_DRAWN: "card-drawn",
  TURN_CHANGED: "TURN_CHANGED",
  CARD_PLAYED: "card-played",
  PLAYER_LOOKS_AT_THE_FUTURE: "player-looks-at-the-future",
  COMBO_PLAYED: "COMBO_PLAYED",
  NOPE_PLAYED: "NOPE_PLAYED",
  NOPE_WINDOW_RESOLVED: "NOPE_WINDOW_RESOLVED",
  EXPLODING_KITTEN_DRAWN: "EXPLODING_KITTEN_DRAWN",
  PLAYER_DEFUSED: "PLAYER_DEFUSED",
  PLAYER_ELIMINATED: "PLAYER_ELIMINATED",
  KITTEN_INSERTED: "KITTEN_INSERTED",
  DECK_SHUFFLED: "DECK_SHUFFLED",
  TURN_SKIPPED: "TURN_SKIPPED",
  GAME_OVER: "GAME_OVER",
  PLAYER_SAW_THE_FUTURE: "PLAYER_SAW_THE_FUTURE",
  WAITING_FOR_PLAYER_SELECTION: "WAITING_FOR_PLAYER_SELECTION",
  PLAYER_SELECTED: "PLAYER_SELECTED",
  WAITING_FOR_CARD_ID_SELECTION: "WAITING_FOR_FAVOR_CARD_SELECTION",
  WAITING_FOR_CARD_INDEX_SELECTION: "WAITING_FOR_RANDOM_CARD_SELECTION",
  WAITING_FOR_CARD_TYPE_SELECTION: "WAITING_FOR_CARD_TYPE_SELECTION",
  CARD_GIVEN: "CARD_GIVEN",
  CARD_STOLEN: "CARD_STOLEN",
  NO_CARD_OF_REQUESTED_TYPE: "NO_CARD_OF_REQUESTED_TYPE",
} as const;

export const ServerPrivateEvents = {
  LEFT_GAME: "left-game",
  WAITING_STATE: "waiting-state",
  GAME_STATE: "game-state",
  CARD_RECEIVED: "card-received",
  GAME_STARTED: "game-started",
  CARD_REMOVED: "card-removed",
  FRIEND_ONLINE_STATUS_CHANGED: "friend-online-status-changed",
  SEE_THE_FUTURE_PEEK: "SEE_THE_FUTURE_PEEK",
  DEFUSE_PROMPT: "DEFUSE_PROMPT",
} as const;

export const ServerErrorEvents = {
  JOIN_GAME_ERROR: "join-game-error",
  LEAVE_GAME_ERROR: "leave-game-error",
  RECONNECT_GAME_ERROR: "reconnect-game-error",
  CONFIRM_START_ERROR: "confirm-start-error",
  CANCEL_START_ERROR: "cancel-start-error",
  DRAW_CARD_ERROR: "draw-card-error",
  PLAY_CARD_ERROR: "play-card-error",
  PLAY_COMBO_ERROR: "play-combo-error",
  PLAY_DEFUSE_ERROR: "play-defuse-error",
  INSERT_KITTEN_ERROR: "insert-kitten-error",
  PLAY_NOPE_ERROR: "play-nope-error",
  SELECT_PLAYER_ERROR: "select-player-error",
  SEEN_THE_FUTURE_ERROR: "seen-the-future-error",
  CHOOSE_CARD_ID_ERROR: "choose-card-id-error",
  CHOOSE_CARD_INDEX_ERROR: "choose-card-index-error",
  CHOOSE_CARD_TYPE_ERROR: "choose-card-type-error",
} as const;
